<?php

declare(strict_types=1);

namespace App\Enum;

enum GameEventTypeEnum: string
{
    case CARD_PLAYED = 'CARD_PLAYED';
    case CARD_DRAWN = 'CARD_DRAWN';
    case DAMAGE_DEALT = 'DAMAGE_DEALT';
    case HEAL_APPLIED = 'HEAL_APPLIED';
    case TURN_ENDED = 'TURN_ENDED';
    case TURN_STARTED = 'TURN_STARTED';
    case DICE_ROLLED = 'DICE_ROLLED';
    case CARD_RUNTIME_VALUE = 'CARD_RUNTIME_VALUE';
    case CARD_DISCARDED = 'CARD_DISCARDED';
    case EFFECT_ADDED = 'EFFECT_ADDED';
    case CARD_CONSUMED = 'CARD_CONSUMED';
    case CARD_PLACED_IN_PLAY_AREA = 'CARD_PLACED_IN_PLAY_AREA';
    case CARD_PLACED_IN_MONSTER_AREA = 'CARD_PLACED_IN_MONSTER_AREA';
    case CARD_STATE_UPDATED = 'CARD_STATE_UPDATED';
    case CARD_ACTION_PREVENTED = 'CARD_ACTION_PREVENTED';
    case COINS_GAINED = 'COINS_GAINED';
    case COINS_LOST = 'COINS_LOST';
    case PLAYER_DIED = 'PLAYER_DIED';
    case MONSTER_DIED = 'MONSTER_DIED';
    case ATTACKED = 'ATTACKED';
    case CARD_GENERATED = 'CARD_GENERATED';
    case CARD_REDRAWN = 'CARD_REDRAWN';
    case CARD_STOLEN = 'CARD_STOLEN';
}
