services:
  php:
    image: ghcr.io/fan2shrek/tcg/api:latest
    ports:
      - "8000:80"
    environment:
      APP_ENV: prod
      DATABASE_URL: mysql://root:${DB_ROOT_PASSWORD}@db:3306/app
      MERCURE_URL: http://mercure/.well-known/mercure
      MERCURE_PUBLIC_URL: https://mercure.esgi.wiatr.fr/.well-known/mercure
      MERCURE_JWT_SECRET: ${MERCURE_JWT_SECRET}
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - app

  front:
    image: ghcr.io/fan2shrek/tcg/frontend:latest
    ports:
      - "3000:3000"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    environment:
      HOSTNAME: "0.0.0.0"
      PORT: 3000
    networks:
      - app

  db:
    image: mariadb:11.8.2
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: app
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - db_root_password
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    networks:
      - app

  dozzle:
    image: amir20/dozzle:latest
    environment:
      DOZZLE_MODE: swarm
      DOZZLE_ENABLE_ACTIONS: 'true'
      DOZZLE_ENABLE_SHELL: 'true'
      DOZZLE_AUTH_PROVIDER: simple
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - source: dozzle_users
        target: /data/users.yml
        mode: 0444
    ports:
      - "9000:8080"
    networks:
      - app
    deploy:
      mode: global

  redis:
    image: redis:7
    deploy:
      replicas: 1
    networks:
      - app

  mercure:
    image: dunglas/mercure
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_JWT_SECRET}
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins https://front.esgi.wiatr.fr
    ports:
      - "8080:80"
    volumes:
      - mercure_data:/data
      - mercure_config:/config
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    networks:
      - app

secrets:
  db_root_password:
    external: true
  dozzle_users:
    external: true

volumes:
  db_data:
  mercure_data:
  mercure_config:

networks:
  app:
    external: true
