services:
  infisical:
    image: infisical/infisical:latest-postgres
    ports:
      - "8081:8080"
    entrypoint:
      - /bin/sh
      - -c
      - "export ENCRYPTION_KEY=$$(cat /run/secrets/infisical_encryption_key) && export AUTH_SECRET=$$(cat /run/secrets/infisical_auth_secret) && export DB_PASSWORD=$$(cat /run/secrets/infisical_db_password) && export DB_CONNECTION_URI=postgresql://infisical:$$DB_PASSWORD@infisical-db:5432/infisical && update-ca-certificates && exec node --enable-source-maps dist/main.mjs"
    environment:
      NODE_ENV: production
      REDIS_URL: "redis://infisical-redis:6379"
      SITE_URL: "https://infisical-esgi.wiatr.fr"
    secrets:
      - infisical_encryption_key
      - infisical_auth_secret
      - infisical_db_password
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - infisical

  infisical-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: infisical
      POSTGRES_PASSWORD_FILE: /run/secrets/infisical_db_password
      POSTGRES_DB: infisical
    volumes:
      - infisical_pg_data:/var/lib/postgresql/data
    secrets:
      - infisical_db_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U infisical"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    networks:
      - infisical

  infisical-redis:
    image: redis:7
    deploy:
      replicas: 1
    networks:
      - infisical

secrets:
  infisical_encryption_key:
    external: true
  infisical_auth_secret:
    external: true
  infisical_db_password:
    external: true

volumes:
  infisical_pg_data:

networks:
  infisical:
    external: true
