export const GameEventType = {
  ATTACKED: "ATTACKED",
  CARD_PLAYED: "CARD_PLAYED",
  CARD_DRAWN: "CARD_DRAWN",
  DAMAGE_DEALT: "DAMAGE_DEALT",
  HEAL_APPLIED: "HEAL_APPLIED",
  TURN_ENDED: "TURN_ENDED",
  TURN_STARTED: "TURN_STARTED",
  ROUND_STARTED: "ROUND_STARTED",
  DICE_ROLLED: "DICE_ROLLED",
  CARD_RUNTIME_VALUE: "CARD_RUNTIME_VALUE",
  CARD_DISCARDED: "CARD_DISCARDED",
  EFFECT_ADDED: "EFFECT_ADDED",
  CARD_PLACED_IN_PLAY_AREA: "CARD_PLACED_IN_PLAY_AREA",
  CARD_PLACED_IN_MONSTER_AREA: "CARD_PLACED_IN_MONSTER_AREA",
  CARD_STATE_UPDATED: "CARD_STATE_UPDATED",
  MONSTER_DIED: "MONSTER_DIED",
  CARD_ACTION_PREVENTED: "CARD_ACTION_PREVENTED",
  COINS_GAINED: "COINS_GAINED",
  COINS_LOST: "COINS_LOST",
  CARD_STOLEN: "CARD_STOLEN",
  CARD_REDRAWN: "CARD_REDRAWN",
  CURRENT_PLAYER_SET: "CURRENT_PLAYER_SET",
  CARD_TRIGGERED_ACTION: "CARD_TRIGGERED_ACTION",
} as const;

export type GameEventTypeEnum =
  (typeof GameEventType)[keyof typeof GameEventType];
