php-version = "8.4"

[source]
paths = [
  "src",
]
includes = ["vendor"]
excludes = []

[formatter]
print-width = 120
tab-width = 4
use-tabs = false
null-type-hint = "question"
space-around-concatenation-binary-operator = false

[linter]
integrations = ["symfony"]

[linter.rules]
ambiguous-function-call = { enabled = false }
literal-named-argument = { enabled = false }
halstead = { effort-threshold = 7000 }
strict-types = { enabled = false }

[analyzer]
find-unused-definitions = true
find-unused-expressions = false
analyze-dead-code = false
check-throws = true
allow-possibly-undefined-array-keys = true
ignore = ["missing-override-attribute"]
excludes = ["src/DataFixtures"]
