name: API code check

on:
  pull_request:
    paths:
      - 'api/**'

permissions:
  pull-requests: write
  issues: write
  contents: read

jobs:
  install-deps:
    name: Install Composer Dependencies
    runs-on: ubuntu-latest
    env:
      WITH_DOCKER: 0

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.composer/cache
            api/vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.5

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist
        working-directory: api

  stan:
    name: PHP Static Analysis
    runs-on: ubuntu-latest
    needs: install-deps
    env:
      WITH_DOCKER: 0

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Cache Composer dependencies
        uses: actions/cache@v6
        with:
          path: |
            ~/.composer/cache
            api/vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.5

      - name: Run static analysis
        run: make stan

  phpunit:
    name: PHP tests
    runs-on: ubuntu-latest
    needs: install-deps
    env:
      WITH_DOCKER: 0
      DATABASE_URL: mysql://root:root@127.0.0.1:3306/app?serverVersion=10.4.34-MariaDB&charset=utf8mb4

    services:
      mariadb:
        image: mariadb:11.8
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: app

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Cache Composer dependencies
        uses: actions/cache@v6
        with:
          path: |
            ~/.composer/cache
            api/vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.5
          coverage: pcov

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v24
        if: github.event_name == 'pull_request'
        with:
          workflow: api_tests_metrics.yml
          name: phpunit-baseline
          branch: main
          path: .

      - name: Setup tests environment
        run: make setup-tests

      - name: Run tests
        id: tests
        run: |
          ./resources/generate_tests_result.php ./baseline.json 2>&1 | tee result.log
          EXITCODE=${PIPESTATUS[0]}

          echo "output<<EOF" >> $GITHUB_OUTPUT
          cat result.log >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          if [ $EXITCODE -ne 0 ]; then
            echo "test failed with exit code $EXITCODE"
            cat result.log
            exit $EXITCODE
          fi

      - name: Find Comment
        uses: peter-evans/find-comment@v4
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: "## 🧪 PHPUnit Report"

      - name: Comment json-verify result on PR
        if: steps.verify.outcome != 'success'
        continue-on-error: true
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: replace
          body: |
            ## 🧪 PHPUnit Report

            ${{ steps.tests.outputs.output }}

  replay:
    name: PHP replay test
    runs-on: ubuntu-latest
    needs: install-deps
    env:
      WITH_DOCKER: 0

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.composer/cache
            api/vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.5

      - name: Run Replays
        run: make tests-replay
